notifications:
  email: false

git:
  depth: 3
  
env:
  global:
    - pyv=3.5

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      env:
        - osv=MacOSX
      before_install:
        - brew update
        - brew install gcc

    - os: linux
      sudo: true
      dist: trusty
      env:
        - osv=Linux
      addons:
          apt:
            sources:
            - ubuntu-toolchain-r-test
            packages:
            - gfortran-5
      before_install:
        - mkdir -p $HOME/.local/bin
        - ln -fs /usr/bin/gfortran-5 "$HOME/.local/bin/gfortran"
        - gfortran --version

install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-$osv-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes --quiet conda
    - conda create --yes --quiet -n test python=$pyv
    - source activate test
    - pip -q install coveralls
    - python setup.py develop

script:
    - coverage run tests/test.py

after_success:
    - coveralls
