sudo: required
git:
  depth: 1
language: python
python:
  - "3.4"
  - "2.7"
before_install:
  - if [[ $(python --version 2>&1) == "Python 3."* ]]; then
     pyv=3;
    fi
  - conda update --yes conda
  - python --version #just checking

install:
 - if [[ -z $pyv ]]; then
   pip -q install coveralls;
  fi
 - sudo apt-get update && sudo apt-get install python-opencv python-numpy
 - python setup.py develop

script:
  - if [[ -z $pyv ]]; then
        echo "running coverage";
        coverage run test/test.py;
    else
        nosetests -v test/test.py;
    fi

after_success:
  - if [[ -z $pyv ]]; then
     coveralls;
    fi
